[package]
name = "mcnbt"
version = "0.2.0"
authors = ["Jonas da Silva"]
edition = "2021"
description = "Read and write NBT"
repository = "https://github.com/phoenixr-codes/mcnbt"
license = "MIT"
keywords = ["minecraft", "nbt", "parser"]
categories = []

[dependencies]
num-traits = "0.2.17"
residua-mutf8 = "2.0.0"
